# Generated by Django 4.2.7 on 2023-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_userdetail_adress_alter_userdetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='adress',
        ),
    ]
