# Generated by Django 4.2.7 on 2023-11-15 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(default='image-2282302_960_720.png', null=True, upload_to='profile_img')),
            ],
        ),
    ]
